# Change these first
owner: gonzalezrujano # Your GitHub organization or username, where this repository lives
repo: sigloxxi_status # The name of this repository

sites:
  - name: Página principal
    url: https://colegiosigloxxi.net
  - name: Registro de alumnos nuevos
    url: https://register.colegiosigloxxi.net
  - name: Control de pagos
    url: https://pagos.colegiosigloxxi.net/auth/login
  - name: Aula virtual
    url: https://aula.colegiosigloxxi.net/auth/login

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /sigloxxi_status
  logoUrl: https://raw.githubusercontent.com/gonzalezrujano/sigloxxi_status/master/assets/logo_sigloxxi.png
  name: Colegio SigloXXI
  introTitle: "Monitor y página de estatus para los sistemas web del colegio SigloXXI."
  introMessage: A continuación, se enlistan los servicios monitorizados por el sistema.
  navbar:
    - title: Status
      href: /sigloxxi_status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
