# Change these first
owner: gonzalezrujano # Your GitHub organization or username, where this repository lives
repo: sigloxxi_status # The name of this repository

sites:
  - name: Página principal
    url: https://colegiosigloxxi.net
  - name: Registro de alumnos nuevos
    url: https://register.colegiosigloxxi.net
  - name: Control de pagos
    url: https://pagos.colegiosigloxxi.net/auth/login
  - name: Aula virtual
    url: https://aula.colegiosigloxxi.net/auth/login

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /sigloxxi_status
  logoUrl: https://raw.githubusercontent.com/gonzalezrujano/sigloxxi_status/master/assets/logo_sigloxxi.png
  name: Colegio SigloXXI
  introTitle: "Monitor estatus para los sistemas web del colegio SigloXXI."
  introMessage: A continuación, se enlistan los servicios monitorizados por el sistema.
  navbar:
    - title: Estatus
      href: /sigloxxi_status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
  degradedPerformance: "El tiempo de respuesta de los procesos no es óptimo"
  completeOutage: "Sistemas caídos completamente"
  partialOutage: "Sistemas caídos parcialmente"
  history: "Historial"
  responseTime: "Tiempo de respuesta"
  up: "Funcionando"
  degraded: "Funcionando parcialmente"
  down: "No funciona"
  responseTimeGraphAlt: "Gráfico de tiempo de respuesta"
  responseTimeDay: "Tiempos de respuesta las últimas 24 horas"
  responseTimeWeek: "Tiempos de respuesta los últimos 7 dias"
  responseTimeMonth: "Tiempos de respuesta los últimos 30 dias"
  responseTimeYear: "Tiempos de respuesta el último año"
  uptime: "Funcionando desde siempre"
  uptimeDay: "Funcionando las ultimas 24 horas"
  uptimeWeek: "Funcionando los últimos 7 dias"
  uptimeMonth: "Funcionando el último mes"
  uptimeYear: "Funcionando el último año"
  liveStatus: "Estatus en vivo"
  liveStatusHtmlComment: "<!--estatus en vivo-->"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
